INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Alabama');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Alaska');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Arizona');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Arkansas');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('California');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Colorado');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Connecticut');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Delaware');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Florida');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Georgia');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Hawaii');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Idaho');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Illinois');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Indiana');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Iowa');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Kansas');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Kentucky');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Louisiana');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Maine');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Maryland');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Massachusetts');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Michigan');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Minnesota');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Mississippi');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Missouri');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Montana');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Nebraska');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Nevada');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('New Hampshire');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('New Jersey');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('New Mexico');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('New York');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('North Carolina');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('North Dakota');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Ohio');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Oklahoma');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Oregon');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Pennsylvania');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Rhode Island');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('South Carolina');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('South Dakota');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Tennessee');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Texas');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Utah');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Vermont');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Virginia');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Washington');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('West Virginia');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Wisconsin');
INSERT INTO uw_queryx1dyn_thing (uw_nam) VALUES ('Wyoming');
